#ifndef JOB_GOVERNOR_PROCESS_H_INCLUDED
#define JOB_GOVERNOR_PROCESS_H_INCLUDED

#include "process.h"

enum class Job_Governor_Process_Steps{
    JOB_GOVERNOR_PROCESS_BLOCKED_WAITING_FOR_USER_MEMORY_RESOURCE,
    JOB_GOVERNOR_PROCESS_FREE_LOADER_PACKAGE_RESOURCE,
    JOB_GOVERNOR_PROCESS_BLOCKED_WAITING_FROM_LOADER_RESOURCE,
    JOB_GOVERNOR_PROCESS_BLOCKED_WAITING_FOR_USER_MEMORY_FOR_PAGING_TABLE,
    JOB_GOVERNOR_PROCESS_CREATE_PROCESS_VIRTUAL_MACHINE,
    JOB_GOVERNOR_PROCESS_BLOCKED_WAITING_FOR_FROM_INTERRUPT_RESOURCE,
    JOB_GOVERNOR_PROCESS_STOP_PROCESS_VIRTUAL_MACHINE,
    JOB_GOVERNOR_PROCESS_CHECK_IO_INTERRUPT,
    JOB_GOVERNOR_PROCESS_CHECK_IO_REACHED_LIMIT,
    JOB_GOVERNOR_PROCESS_FREE_STRING_IN_MEMORY_RESOURCE_WITH_INFO_REACHED_LIMIT,
    JOB_GOVERNOR_PROCESS_CHEKC_GEDA_INTERRUPT,
    JOB_GOVERNOR_PROCESS_BLOCKED_WAITING_FOR_USER_INPUT_RESOURCE,
    JOB_GOVERNOR_PROCESS_ACTIVATE_PROCESS_VIRTUAL_MACHINE,
    JOB_GOVERNOR_PROCESS_CHECK_BP_BG_INTERRUPT,
    JOB_GOVERNOR_PROCESS_BLOCKED_WAITING_FOR_CHANNEL_DEVICE_RESOURCE,
    JOB_GOVERNOR_PROCESS_SET_CHANNEL_DEVICE_REGISTERS_AND_XCHG,
    JOB_GOVERNOR_PROCESS_FREE_CHANNEL_DEVICE_RESOURCE,
    JOB_GOVERNOR_PROCESS_CHECK_PSTR_PUTA_INTERRUPT,
    JOB_GOVERNOR_PROCESS_FREE_STRING_IN_MEMORY_RESOURCE_WITH_INFO_OUTPUT_CONTENT,
    JOB_GOVERNOR_PROCESS_REMOVE_PROCESS_VIRTUAL_MACHINE,
    JOB_GOVERNOR_PROCESS_FREE_USER_MEMORY_RESOURCE,
    JOB_GOVERNOR_PROCESS_FREE_PIE_IN_THE_OVEN_RESOURCE,
    JOB_GOVERNOR_PROCESS_FREE_SYSTEM_COMMAND_RESOURCE,
    JOB_GOVERNOR_PROCESS_BLOCKED_WAITING_FOR_NONEXISTANT_RESOURCE
};

class Job_Governor_Process: public Process{
    private:
        Job_Governor_Process_Steps steps;
    public:
        Job_Governor_Process(Saved_Registers saved_registers, uint16_t unique_id, Kernel* kernel, CPU* cpu, Process* parent_process, std::vector<Process*> friend_processes, std::string username);
        ~Job_Governor_Process();
        virtual int8_t execute() override;
};


#endif // JOB_GOVERNOR_PROCESS_H_INCLUDED