#ifndef JOB_CONTROL_LANGUAGE_PROCESS_H_INCLUDED
#define JOB_CONTROL_LANGUAGE_PROCESS_H_INCLUDED

#include "process.h"

#define JOB_CONTROL_LANGUAGE_PROCESS_MSG_BYE_NOT_FOUND "#BYE not found\n"
#define JOB_CONTROL_LANGUAGE_PROCESS_MSG_LOS_NOT_FOUND "#LOD not found\n"


enum class Job_Control_Language_Process_Steps{
    JOB_CONTROL_LANGUAGE_PROCESS_BLOCKED_WAIT_FOR_TASK_IN_SUPERVISOR,
    JOB_CONTROL_LANGUAGE_PROCESS_INITIALIZE_PROGRAM_LIST,
    JOB_CONTROL_LANGUAGE_PROCESS_TAKE_BLOCK_FROM_SUPERVISOR_MEMORY_1,
    JOB_CONTROL_LANGUAGE_PROCESS_CHECK_IF_BLOCK_IS_LOS,
    JOB_CONTROL_LANGUAGE_PROCESS_ATTACH_BLOCK_TO_PROGRAM_LIST,
    JOB_CONTROL_LANGUAGE_PROCESS_TAKE_BLOCK_FROM_SUPERVISOR_MEMORY_2,
    JOB_CONTROL_LANGUAGE_PROCESS_CHECK_IF_BLOCK_IS_BYE_OR_IS_IT_LAST_BLOCK,
    JOB_CONTROL_LANGUAGE_PROCESS_CHECK_IF_BLOCK_IS_BYE,
    JOB_CONTROL_LANGUAGE_PROCESS_ATTACH_BOCK_TO_PROGRAM_LIST_AND_CREATE_RESOURCE_LOADER_PACKAGE,
    JOB_CONTROL_LANGUAGE_PROCESS_FREE_RESOURCE_PIE_IN_THE_OVEN,
    JOB_CONTROL_LANGUAGE_PROCESS_FREE_RESOURCE_STRING_IN_MEMORY_WITH_INFO_BYE_NOT_FOUND,
    JOB_CONTROL_LANGUAGE_PROCESS_FREE_RESOURCE_STRING_IN_MEMORY_WITH_INFO_LOS_NOT_FOUND,
    JOB_CONTROL_LANGUAGE_PROCESS_FREE_RESOURCE_SYSTEM_COMMAND,
}; 

class Job_Control_Language_Process: public Process{
    private:
        Job_Control_Language_Process_Steps step;
    public:
        Job_Control_Language_Process(Kernel* kernel, Process* parent_process, std::vector<Process*> friend_processes, std::string username);
        ~Job_Control_Language_Process();
        Process_State execute() override; 
};






#endif // JOB_CONTROL_LANGUAGE_PROCESS_H_INCLUDED